c_compiler_version:
- 5.4
cxx_compiler_version:
- 5.4
cudnn:
- 7.6
channel_sources:
- deepmodeling,defaults
channel_targets:
- deepmodeling main
cuda_compiler_version:  
- None
#- 9.2
#- 10.0
#- 10.1  
- 11.0
docker_image:
- quay.io/condaforge/linux-anvil-comp7
- quay.io/condaforge/linux-anvil-cuda:11.0
