{% set version = "2.1.0" %}

{% if cuda_compiler_version == "None" %}
{% set tflow_variant = "cpu" %}
{% else %}
{% set tflow_variant = "gpu" %}
{% endif %}
# This is the recipe for the "gpu" variant of tensorflow-base
package:
  name: libtensorflow_cc
  version: {{ version | replace("-", "_") }}

source:
  fn: tensorflow-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: 638e541a4981f52c69da4a311815f1e7989bf1d67a41d204511966e1daed14f7
  patches:
    - 0002-do-not-include-B-usr-bin-flag.patch  # [cuda_compiler_version != 'None']

build:
  number: 0
  string: {{ tflow_variant }}_h{{PKG_HASH}}_{{ PKG_BUILDNUM }}
  skip: True  # [not x86_64]
  skip: True  # [win and vc<14]
  skip: True  # [not linux]
  skip: True  # [not py==37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel
    - rsync
  host:
    - cudatoolkit {{ cudatoolkit }}*  # [cuda_compiler_version != 'None']
    - cudnn {{ cudnn }}*  # [cuda_compiler_version != 'None']
    - cupti  # [cuda_compiler_version != 'None']
    - python
    - numpy
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [cuda_compiler_version != 'None']
    - {{ pin_compatible('cudnn') }}  # [cuda_compiler_version != 'None']
    - cupti  # [cuda_compiler_version != 'None']

test:
  files:
    - test_cc.cc
  requires:
    - {{ compiler('cxx') }}
  commands:
    - test -f $PREFIX/lib/libtensorflow_cc.so  # [not win]
    - $CXX -std=c++11 -o test_cc -L${PREFIX}/lib/ -ltensorflow_cc -ltensorflow_framework -lrt -I${PREFIX}/include/ test_cc.cc && ./test_cc  # [not win]

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library, base GPU package, tensorflow only.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base GPU package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  tflow_variant: {{ tflow_variant }}
